spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?serverTimezone=UTC
    username: root
    password: 131415
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 20MB
      # 设置总上传的文件大小
      max-request-size: 100MB
      enabled: true
  tomcat:
    remote-ip-header: x-forward-for
    uri-encoding: UTF-8
    max-threads: 1000
    max-http-header-size: 8096

server:
  tomcat:
    max-swallow-size: -1 #重要的一行，修改tomcat的吞吐量

#mybatis:
#  mapper-locations: classpath:mapper/*.xml    # mapper映射文件位置
#  type-aliases-package: com.susu.damain    # 实体类所在的位置


aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: #
    accessKeySecret: #
    bucketName: #
    customDomain: https://oss.qingmumu.xyz

sa-token:
  #一周
  timeout: 604800

amap:
  key: 187dacc112e3d2a9f4e4c35f8f7d108f